### ISSUE TITLE
What's the purpose of xarray-gdal?

### ISSUE THREAD

**Issue by meteoDaniel** [bopen/xarray-gdal#1]
Dear @alexamici please avoid any dependecies to GDAL. It's a mess to install GDAL. 

Nevertheless, what's the purpose of this project? 

Best regards

**Comment by alexamici** [comment]
The purpose of the project is to experiment how to best map the GDAL data model to the xarray / netCDF one. Hard to do without GDAL. The package is not intender for public release.

I clarified these points in the README.

BTW, I'm one of the authors of the original GDAL build system and I created the first Debian package for it almost 20 years ago. It is always a pleasure to see your voluntary work recognised.

**Comment by meteoDaniel** [comment]
But why it is such a mess to run on ubuntu or other platforms? You can find hundreds of stackoverflow articles according to installation process of GDAL?

**Comment by alexamici** [comment]
No idea. I just type `apt-get install gdal-bin python-gdal` since as long as I can remember (I created the Debian package for a reason!)

Nowadays I tend to use `conda` packages more often than system dependencies and so `conda install -c conda-forge gdal` is how I install GDAL on MacOS, Linux and Windows.

**Comment by meteoDaniel** [comment]
I am very sorry If my initial post sounds angry to you. I just wanted to open a discussion with you. 

So If i type in `apt-get install gdal-bin python-gdal` i immediately run into the first issue: 

```
E: Package 'python-gdal' has no installation candidate
```

E.g. installing wradlib package (depends on GDAL) I had several problems and finally I use these lines in my dockerfile 

```
RUN wget https://download.osgeo.org/proj/proj-7.2.0.tar.gz
RUN tar xvzf proj-7.2.0.tar.gz && cd proj-7.2.0 && ./configure --without-curl && make && make install
RUN cd /
RUN wget download.osgeo.org/gdal/3.0.4/gdal304.zip
RUN unzip gdal304.zip && cd gdal-3.0.4 && ./configure && make clean && make && make install
ENV LD_LIBRARY_PATH=/usr/local/lib
```
This took me in sum 5 working days over the last months. I am very sure that your attempt would not work here. Let me check this out.

## Update: 
I have run the installation as you mentioned, and now I have the problem that the pypi package GDAL can't be installed:
```
    __main__.gdal_config_error: [Errno 2] No such file or directory: 'gdal-config'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/ae/09/cac5021db34f5c95c6a660b90e5d27062a520fe32a0493f68d07a7055d30/GDAL-3.0.4.tar.gz#sha256=a17eaa6872e4b7f7fa82f86aeccecc57d224bd054952a56db64368ecaf18509c (from https://pypi.org/simple/gdal/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement GDAL==3.0.4
ERROR: No matching distribution found for GDAL==3.0.4
``` 
And such errors happen very often. Maybe the users of GDAL using it in the wrong way or I am stupid on this point. But wradlib won't work with the GDAL pypi package. This is why i am struggling several times with GDAL.

**Comment by alexamici** [comment]
You are right, it was `python3-gdal`. I stand corrected.
```
$ sudo apt-get install gdal-bin python3-gdal
$ gdalinfo --version
GDAL 3.0.4, released 2020/01/28
$ python3
>>> import gdal
>>> 
```

**Comment by meteoDaniel** [comment]
Nearly the same problem because one of the package (in this special case wradlib) requires GDAL pypi package and tries to install it even when I delete GDAL from my requirements.txt. 

So if you say GDAL is that easy to install I guess the user (here wradlib) makes the mistake or not?

**Comment by alexamici** [comment]
I had never heard of *wradlib*, it looks like a really cool project!
